#!/usr/bin/env python

# "input_dim" : 79,
# "input_dim" : 64,

config = {
"learning_rate" : 0.0001,
"num_epochs" : 500,
"decay" : 1e-5,
"hidden_dim" : 64,
"layer_dim" : 1,
"output_dim" : 15,
"seq_dim" : 2,
"batch_size" :32,
"split_ratio" : 0.2,
"num_workers":4,
"accumulation_steps": 1,
"no_of_subset":30 ,
"subset_overlap_length": 2 ,
"resize_width": 120,
"resize_height": 97,
"image_width": 663,
"image_height": 446,
"ActivityIdList":
         [{'name': 'washDishes', 'id': 0},
         {'name': 'goToBed', 'id': 1},
         {'name': 'brushTeeth', 'id': 2},
         {'name': 'prepareLunch', 'id': 3},
         {'name': 'eating', 'id': 4},
         {'name': 'takeShower', 'id': 5},
         {'name': 'leaveHouse', 'id': 6},
         {'name': 'getDrink', 'id': 7},
         {'name': 'prepareBreakfast', 'id': 8},
         {'name': 'getSnack', 'id': 9},
         {'name': 'idle', 'id': 10},
         {'name': 'grooming', 'id': 11},
         {'name': 'prepareDinner', 'id': 12},
         {'name': 'relaxing', 'id': 13},
         {'name': 'useToilet', 'id': 14}],

"merging_activties" : {
        "loadDishwasher": "washDishes",
        "unloadDishwasher": "washDishes",
        "loadWashingmachine": "washClothes",
        "unloadWashingmachine": "washClothes",
        "receiveGuest": "relaxing",
        "eatDinner": "eating",
        "eatBreakfast": "eating",
        "getDressed": "grooming",
        "shave": "grooming",
        "takeMedication": "idle",
        "leave_Home": "leaveHouse",
        "Sleeping": "goToBed",
        "Bed_to_Toilet": "useToilet",
        "Enter_Home": "idle",
        "Respirate": "relaxing",
        "Work": "idle",
        "Housekeeping": "idle",
        "Idle": "idle",
        "watchTV": "relaxing"
    },
"graph_embedding_ob": False,
"graph_embedding_raw": False,
"master_raw_representation": False,
"master_ob_DeCompressed_representation": False,
"master_ob_Compressed_representation": False,
"raw_data": False,
"ob_data_compressed": False,
"ob_data_Decompressed": False
}

